### ISSUE TITLE
Find one bug

### ISSUE THREAD

**Issue by ChoingHyun** [Sogrey/ExpandableListView#1]
When i user this library in my application,when collapse items again and again,the app will crash:

java.lang.NullPointerException: Attempt to read from field 'android.view.View com.expandableListViewDemo.adapter.MorelevelAdapter$ViewHolderChild.viewBottom' on a null object reference

still now ,I don't konw what happned in the program,please fix the bug if you have time,tks.

**Comment by Sogrey** [comment]
An apology for being late.

This project has been abandoned. Sorry for the inconvenience. Please check [Sogrey/TreeDataView](https://github.com/Sogrey/TreeDataView)
